---
name: "Release"
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"
jobs:
  buf:
    name: "Push BSR tag"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "bufbuild/buf-action@v1"
        with:
          token: "${{ secrets.BUF_REGISTRY_TOKEN }}"
          breaking_against: "https://github.com/authzed/api.git#branch=main"
